site_name: BI and UQ of Fractional-Order Constitutive Models
site_description: Bayesian Calibration and Uncertainty Quantification for Fractional-Order Constitutive Models
site_author: Arman Khoshnevis

repo_url: https://github.com/armankhoshnevis/BI-and-UQ-of-Fractional-Order-Constitutive-Models
repo_name: armankhoshnevis/BI-and-UQ-of-Fractional-Order-Constitutive-Models

theme:
  name: material
  palette:
    scheme: 
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes

plugins:
  - search
  - caption
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Datasets:
      - Experimental Characterization: Datasets_Experimental.md
      - Synthetic Data: Datasets_Synthetic.md
  - Configs: Configs.md
  - Constitutive Modeling and Probabilistic Calibration:
      - Constitutive Models: Constitutive_Models.md
      - Probabilistic Calibration: Probabilistic_Calibration.md
  - API Reference:
      - FMG-FMG Model: Inference_Funcs_FMG.md
      - FMM-FMG Model: Inference_Funcs_FMM.md